AllCops:
  Exclude:
    - 'bin/**/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'db/**/*'
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
