AllCops:
  Exclude:
    - 'bin/**/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'db/**/*'
Bundler/OrderedGems:
  Enabled: true
  TreatCommentsAsGroupSeparators: true
Layout/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 30
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
