AllCops:
  Exclude:
    - 'bin/**/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'db/**/*'
Bundler/OrderedGems:
  Enabled: false
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
