common: &default_settings
  license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  log_level: debug
  app_name: <%= ENV['NEW_RELIC_APP_NAME'] %>

development:
  <<: *default_settings

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings

production:
  <<: *default_settings
