version: v1.0
name: Bangladesh Production Deployment
blocks:
  - name: Deploy to Bangladesh Production
    task:
      jobs:
        - name: Deploy to Bangladesh Production
          commands:
            - checkout
            - sem-version ruby 2.5.1
            - cache restore
            - yarn install
            - bundle install --deployment --path vendor/bundle
            - cache store
            - 'bundle exec cap bangladesh:production deploy'
      secrets:
        - name: semaphore-deploy-key
      prologue:
        commands:
          - chmod 600 ~/.ssh/semaphore_id_rsa
          - ssh-add ~/.ssh/semaphore_id_rsa
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
