version: v1.0
name: Ethiopia Production Deployment
blocks:
  - name: Deploy to Ethiopia Production
    task:
      jobs:
        - name: Deploy to Ethiopia Production
          commands:
            - git clone https://github.com/simpledotorg/deployment
            - cd deployment
            - git checkout add-ethiopia-hosts
            - cd standalone
            - make init
            - make deploy hosts=ethiopia/production password_file=~/.ansible/password_file
      secrets:
        - name: ansible
        - name: semaphore-deploy-key
      prologue:
        commands:
          - chmod 600 ~/.ssh/semaphore_id_rsa
          - ssh-add ~/.ssh/semaphore_id_rsa
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
