version: v1.0
name: Ethiopia Production Deployment
blocks:
  - name: Deploy to Ethiopia Production
    task:
      jobs:
        - name: Deploy to Ethiopia Production
          env:
            SEMAPHORE_GIT_URL: https://github.com/simpledotorg/deployment
          commands:
            - checkout
            - cd deployment/standalone
            - make deploy hosts=ethiopia.production password_file=~/.ansible/password_file
      secrets:
        - name: ansible
      prologue:
        commands:
          - chmod 600 ~/.ssh/semaphore_id_rsa
          - ssh-add ~/.ssh/semaphore_id_rsa
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
