name: Review Mobile App Build

on: pull_request

jobs:
  build_app:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout simple-android
        uses: actions/checkout@v2
        with:
          repository: simpledotorg/simple-android
          path: simple-android

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build APK
        run: simple-android/gradlew -p simple-android -PqaManifestEndpoint="https://simple-review-pr-${{github.event.pull_request.number}}.herokuapp.com/api/" app:assembleQaDebug

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: review-mobile-app-${{github.event.pull_request.number}}
          path: simple-android/app/build/outputs/apk/qa/debug/app-qa-debug.apk

    qa_android_tests:
      runs-on: [macos-latest]
      steps:
        - name: Checkout simple-android
          uses: actions/checkout@v2
          with:
            repository: simpledotorg/simple-android
            path: simple-android

        - name: Setup JDK
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

        - name: Turn on capturing of flaky tests
          run: cat app/src/androidTest/resources/quarantine_ci.properties > app/src/androidTest/resources/quarantine.properties

        - name: QA Android Tests
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 29
            script: simple-android/gradlew -p simple-android -PqaManifestEndpoint="https://simple-review-pr-${{github.event.pull_request.number}}.herokuapp.com/api/" connectedQaDebugAndroidTest
