name: Mark stale pull requests

on:
  schedule:
  - cron: "* * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'This PR is stale. Please review/update it or close it.'
        stale-pr-label: 'stale-pr'
        days-before-stale: 20
